warnings:
  classes:
    CartWidget:
      message: 'Widgets are no longer part of SS4'
    ShopAccountFormValidator:
      message: 'No longer needed in SS4, as it was only used to fix an issue in 3.x'
    DashboardRecentMembersPanel:
      message: 'removed'
    DashboardRecentOrdersChart:
      message: 'removed'
    DashboardRecentOrdersPanel:
      message: 'removed'
    Zone:
      message: 'Zones have been moved to the shipping module'
    ZoneRegion:
      message: 'Zones have been moved to the shipping module'
    ZoneAdmin:
      message: 'Zones have been moved to the shipping module'
    ShopEmail:
      message: 'Has been replaced with the SilverStripe 4 SwiftMailer integration'
mappings:
  Payment: SilverShop\Payment
  Shop: SilverShop\Generic
  ProductGroup: SilverShop\Includes\ProductGroup
  ProductMenu: SilverShop\Includes\ProductMenu
  PriceTag: SilverShop\Includes\PriceTag
  MemberForm: SilverShop\Forms\ShopAccountForm
  ShopSideReport: SilverShop\Reports\SideReport
  AccountPage: SilverShop\Page\AccountPage
  AccountPage_Controller: SilverShop\Page\AccountPageController
  OrderActionsForm: SilverShop\Forms\OrderActionsForm
  OrderActionsForm_Validator: SilverShop\Forms\OrderActionsFormValidator
  OrderManipulation: SilverShop\Extension\OrderManipulationExtension
  ShopAccountForm: SilverShop\Forms\ShopAccountForm
  ShopMemberFactory: SilverShop\Checkout\ShopMemberFactory
  RestrictionRegionCountryDropdownField: SilverShop\Forms\RestrictionRegionCountryDropdownField
  SetLocationForm: SilverShop\Forms\SetLocationForm
  LocationFormPageDecorator: SilverShop\Extension\LocationFormPageExtension
  CartEditField: SilverShop\Forms\CartEditField
  CartForm: SilverShop\Forms\CartForm
  CartPage: SilverShop\Page\CartPage
  CartPage_Controller: SilverShop\Page\CartPageController
  MatchObjectFilter: SilverShop\ORM\Filters\MatchObjectFilter
  OrderTotalCalculator: SilverShop\Cart\OrderTotalCalculator
  ShoppingCart: SilverShop\Cart\ShoppingCart
  ShoppingCart_Controller: SilverShop\Cart\ShoppingCartController
  ShopQuantityField: SilverShop\Forms\ShopQuantityField
  DropdownShopQuantityField: SilverShop\Forms\DropdownShopQuantityField
  ViewableCart: SilverShop\Extension\ViewableCartExtension
  Checkout: SilverShop\Checkout\Checkout
  CheckoutComponentValidator: SilverShop\Forms\CheckoutComponentValidator
  CheckoutConfig: SilverShop\Checkout\CheckoutConfig
  CheckoutFieldFactory: SilverShop\Checkout\CheckoutFieldFactory
  CheckoutForm: SilverShop\Forms\CheckoutForm
  CheckoutPage: SilverShop\Page\CheckoutPage
  CheckoutPage_Controller: SilverShop\Page\CheckoutPageController
  AddressBookCheckoutComponent: SilverShop\Checkout\Component\AddressBook
  ShippingAddressBookCheckoutComponent: SilverShop\Checkout\Component\AddressBookShipping
  BillingAddressBookCheckoutComponent: SilverShop\Checkout\Component\AddressBookBilling
  AddressCheckoutComponent: SilverShop\Checkout\Component\Address
  ShippingAddressCheckoutComponent: SilverShop\Checkout\Component\ShippingAddress
  BillingAddressCheckoutComponent: SilverShop\Checkout\Component\BillingAddress
  CheckoutComponent: SilverShop\Checkout\Component\CheckoutComponent
  CheckoutComponent_Namespaced: SilverShop\Checkout\Component\CheckoutComponentNamespaced
  CheckoutComponentConfig: SilverShop\Checkout\CheckoutComponentConfig
  SinglePageCheckoutComponentConfig: SilverShop\Checkout\SinglePageCheckoutComponentConfig
  CustomerDetailsCheckoutComponent: SilverShop\Checkout\Component\CustomerDetails
  MembershipCheckoutComponent: SilverShop\Checkout\Component\Membership
  NotesCheckoutComponent: SilverShop\Checkout\Component\Notes
  OnsitePaymentCheckoutComponent: SilverShop\Checkout\Component\OnsitePayment
  PaymentCheckoutComponent: SilverShop\Checkout\Component\Payment
  TermsCheckoutComponent: SilverShop\Checkout\Component\Terms
  OrderEmailNotifier: SilverShop\Checkout\OrderEmailNotifier
  OrderProcessor: SilverShop\Checkout\OrderProcessor
  PaymentForm: SilverShop\Forms\PaymentForm
  CheckoutStep: SilverShop\Checkout\Step\CheckoutStep
  CheckoutStep_Address: SilverShop\Checkout\Step\Address
  CheckoutStep_AddressBook: SilverShop\Checkout\Step\AddressBook
  CheckoutStep_ContactDetails: SilverShop\Checkout\Step\ContactDetails
  CheckoutStep_Membership: SilverShop\Checkout\Step\Membership
  CheckoutStep_PaymentMethod: SilverShop\Checkout\Step\PaymentMethod
  CheckoutStep_Summary: SilverShop\Checkout\Step\Summary
  SteppedCheckout: SilverShop\Extension\SteppedCheckoutExtension
  OrdersAdmin: SilverShop\Admin\OrdersAdmin
  OrderGridFieldDetailForm_ItemRequest: SilverShop\Forms\GridField\OrderGridFieldDetailForm_ItemRequest
  ProductBulkLoader: SilverShop\Admin\ProductBulkLoader
  ProductCatalogAdmin: SilverShop\Admin\ProductCatalogAdmin
  ShopConfig: SilverShop\Extension\ShopConfigExtension
  ShopDevelopmentAdmin: SilverShop\Dev\ShopDevelopmentAdmin
  Address: SilverShop\Model\Address
  Buyable: SilverShop\Model\Buyable
  CanBeFreeCurrency: SilverShop\ORM\FieldType\CanBeFreeCurrency
  I18nDatetime: SilverShop\ORM\FieldType\I18nDatetime
  ShopCountry: SilverShop\ORM\FieldType\ShopCountry
  ShopCurrency: SilverShop\ORM\FieldType\ShopCurrency
  MultiFieldPartialMatchFilter: SilverShop\ORM\Filters\MultiFieldPartialMatchFilter
  Order: SilverShop\Model\Order
  OrderAttribute: SilverShop\Model\OrderAttribute
  OrderItem: SilverShop\Model\OrderItem
  OrderItemList: SilverShop\ORM\OrderItemList
  OrderModifier: SilverShop\Model\Modifiers\OrderModifier
  OrderStatusLog: SilverShop\Model\OrderStatusLog
  RegionRestriction: SilverShop\Shipping\Model\RegionRestriction
  ShopMember: SilverShop\Extension\MemberExtension
  ShopPayment: SilverShop\Extension\PaymentExtension
  ShopPaymentService: SilverShop\Extension\PaymentServiceExtension
  OrderModifierForm: SilverShop\Forms\OrderModifierForm
  FreeShippingModifier: SilverShop\Model\Modifiers\Shipping\Free
  PickupShippingModifier: SilverShop\Model\Modifiers\Shipping\Pickup
  ShippingModifier: SilverShop\Model\Modifiers\Shipping\Base
  SimpleShippingModifier: SilverShop\Model\Modifiers\Shipping\Simple
  WeightShippingModifier: SilverShop\Model\Modifiers\Shipping\Weight
  SubTotalModifier: SilverShop\Model\Modifiers\SubTotal
  FlatTaxModifier: SilverShop\Model\Modifiers\Tax\FlatTax
  GlobalTaxModifier: SilverShop\Model\Modifiers\Tax\GlobalTax
  TaxModifier: SilverShop\Model\Modifiers\Tax\Base
  AddProductForm: SilverShop\Forms\AddProductForm
  Product: SilverShop\Page\Product
  Product_Controller: SilverShop\Page\ProductController
  Product_OrderItem: SilverShop\Model\Product\OrderItem
  ProductCategory: SilverShop\Page\ProductCategory
  ProductCategory_Controller: SilverShop\Page\ProductCategoryController
  Product_Image: SilverShop\Extension\ProductImageExtension
  ProductAttributeType: SilverShop\Model\Variation\AttributeType
  ProductAttributeValue: SilverShop\Model\Variation\AttributeValue
  ProductVariation: SilverShop\Model\Variation\Variation
  ProductVariation_OrderItem: SilverShop\Model\Variation\OrderItem
  ProductVariationsExtension: SilverShop\Extension\ProductVariationsExtension
  VariationForm: SilverShop\Forms\VariationForm
  VariationFormValidator: SilverShop\Forms\VariationFormValidator
  AbandonedCartReport: SilverShop\Reports\AbandonedCartReport
  CustomerReport: SilverShop\Reports\CustomerReport
  ProductReport: SilverShop\Reports\ProductReport
  ShopPeriodReport: SilverShop\Reports\ShopPeriodReport
  ShopReport_Query: SilverShop\Reports\ShopReportQuery
  ShopSalesReport: SilverShop\Reports\ShopSalesReport
  ShopSideReport_FeaturedProducts: SilverShop\Reports\SideReport\FeaturedProducts
  ShopSideReport_AllProducts: SilverShop\Reports\SideReport\AllProducts
  ShopSideReport_NoImageProducts: SilverShop\Reports\SideReport\NoImageProducts
  ShopSideReport_HeavyProducts: SilverShop\Reports\SideReport\HeavyProducts
  TaxReport: SilverShop\Reports\TaxReport
  ShopTools: SilverShop\ShopTools
  ShopUserInfo: SilverShop\ShopUserInfo
  CalculateProductPopularity: SilverShop\Tasks\CalculateProductPopularity
  CartCleanupTask: SilverShop\Tasks\CartCleanupTask
  CustomersToGroupTask: SilverShop\Tasks\CustomersToGroupTask
  PopulateCartTask: SilverShop\Tasks\PopulateCartTask
  PopulateShopTask: SilverShop\Tasks\PopulateShopTask
  ProductVariationsFromAttributeCombinations: SilverShop\Tasks\ProductVariationsFromAttributeCombinations
  RecalculateAllOrdersTask: SilverShop\Tasks\RecalculateAllOrdersTask
  ShopEmailPreviewTask: SilverShop\Tasks\ShopEmailPreviewTask
  ShopMigrationTask: SilverShop\Tasks\ShopMigrationTask
  AccountPageTest: SilverShop\Tests\Page\AccountPageTest
  OrderActionsFormTest: SilverShop\Tests\Forms\OrderActionsFormTest
  MatchObjectFilterTest: SilverShop\Tests\ORM\Filters\MatchObjectFilterTest
  ShoppingCartControllerTest: SilverShop\Tests\Cart\ShoppingCartControllerTest
  ShoppingCartTest: SilverShop\Tests\Cart\ShoppingCartTest
  ShoppingCartTest_TestShoppingCartHooksExtension: SilverShop\Tests\Cart\ShoppingCartTest_TestShoppingCartHooksExtension
  ShoppingCartTest_TestShoppingCartErroringHooksExtension: SilverShop\Tests\Cart\ShoppingCartTest_TestShoppingCartErroringHooksExtension
  AddressBookCheckoutComponentTest: SilverShop\Tests\AddressBookCheckoutComponentTest
  CheckoutComponentTest: SilverShop\Tests\CheckoutComponentTest
  CheckoutFormTest: SilverShop\Tests\CheckoutFormTest
  CheckoutPageTest: SilverShop\Tests\CheckoutPageTest
  CheckoutTest: SilverShop\Tests\CheckoutTest
  NestedCheckoutTest: SilverShop\Tests\NestedCheckoutTest
  OrderProcessorTest: SilverShop\Tests\OrderProcessorTest
  OrderProcessorTest_CustomOrderItem: SilverShop\Tests\OrderProcessorTest_CustomOrderItem
  OrderProcessorTest_PlaceFailExtension: SilverShop\Tests\OrderProcessorTest_PlaceFailExtension
  SteppedCheckoutTest: SilverShop\Tests\Extension\SteppedCheckoutExtensionTest
  ProductBulkLoaderTest: SilverShop\Tests\Admin\ProductBulkLoaderTest
  AddressTest: SilverShop\Tests\Model\AddressTest
  ExtendedTestAddress: SilverShop\Tests\Model\ExtendedTestAddress
  CanBeFreeCurrencyTest: SilverShop\Tests\ORM\FieldType\CanBeFreeCurrencyTest
  I18nDatetimeTest: SilverShop\Tests\ORM\FieldType\I18nDatetimeTest
  ShopCountryTest: SilverShop\Tests\ORM\FieldType\ShopCountryTest
  ShopCurrencyTest: SilverShop\Tests\ORM\FieldType\ShopCurrencyTest
  OrderNotificationTest: SilverShop\Tests\Checkout\OrderEmailNotifierTest
  OrderStatusLogTest: SilverShop\Tests\Model\OrderStatusLogTest
  OrderTest: SilverShop\Tests\Model\OrderTest
  OrderTest_TestStatusChangeExtension: SilverShop\Tests\Model\OrderTest_TestStatusChangeExtension
  RegionRestrictionTest: SilverShop\Tests\Model\RegionRestrictionTest
  RegionRestriction_RateTest: SilverShop\Tests\Model\RegionRestriction_RateTest
  ShopMemberTest: SilverShop\Tests\Extension\MemberExtensionTest
  ShopPaymentTest: SilverShop\Tests\Checkout\ShopPaymentTest
  FlatTaxModifierTest: SilverShop\Tests\Model\Modifiers\FlatTaxModifierTest
  GlobalTaxModifierTest: SilverShop\Tests\Model\Modifiers\GlobalTaxModifierTest
  OrderModifierTest: SilverShop\Tests\Model\Modifiers\OrderModifierTest
  OrderModifierTest_TestModifier: SilverShop\Tests\Model\Modifiers\OrderModifierTest_TestModifier
  SimpleShippingModifierTest: SilverShop\Tests\Model\Modifiers\SimpleShippingModifierTest
  AddProductFormTest: SilverShop\Tests\Forms\AddProductFormTest
  CustomProductTest: SilverShop\Tests\Model\Product\CustomProductTest
  CustomProduct: SilverShop\Tests\Model\Product\CustomProduct
  CustomProduct_OrderItem: SilverShop\Tests\Model\Product\CustomProduct_OrderItem
  ProductCategoryTest: SilverShop\Tests\Page\ProductCategoryTest
  ProductImageTest: SilverShop\Tests\Extension\ProductImageExtensionTest
  ProductOrderItemTest: SilverShop\Tests\Model\Product\ProductOrderItemTest
  ProductTest: SilverShop\Tests\Page\ProductTest
  ProductTest_FractionalDiscountExtension: SilverShop\Tests\Page\ProductTest_FractionalDiscountExtension
  ProductVariationTest: SilverShop\Tests\Model\Variation\VariationTest
  ProductVariationVersionTest: SilverShop\Tests\Model\Variation\VariationVersionTest
  ShopReportTest: SilverShop\Tests\Reports\ShopReportTest
  ShopTest: SilverShop\Tests\ShopTest
  ShopTestControllerExtension: SilverShop\Tests\ShopTestControllerExtension
  ShopToolsTest: SilverShop\Tests\ShopToolsTest
  ShopUserInfoTest: SilverShop\Tests\ShopUserInfoTest
  CartCleanupTaskTest: SilverShop\Tests\Tasks\CartCleanupTaskTest
  CartCleanupTaskTest_CartCleanupTaskFake: SilverShop\Tests\Tasks\CartCleanupTaskTest_CartCleanupTaskFake
  ViewableCartTest: SilverShop\Tests\Extension\ViewableCartExtensionTest
## Migrate translations…
#  ShopDashboard: REMOVE\ShopDashboard
#  Variation: REMOVE\Variation
#  OrderAdmin: MOVE\SilverShop\Admin\OrdersAdmin
#  OrderForm: MOVE\SilverShop\Forms\OrderActionsForm
#  CreateAddressForm: MOVE\SilverShop\Model\Address
#  PaymentProcessor: MOVE\SilverShop\Checkout\OrderProcessor
