<% if FullName %>$FullName<br/><% end_if %>
<% if Compnay %>$Compnay<br/><% end_if %>
<% if Address %>$Address<br/><% end_if %>
<% if AddressLine2 %>$AddressLine2<br/><% end_if %>
<% if City %>$City<br/><% end_if %>
<% if PostalCode %>$PostalCode<br/><% end_if %>
<% if State %>$State<% end_if %>
<% if Country %>$Country<br/><% end_if %>
<% if Phone %>$Phone<% end_if %>