name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      composer_require_extra:
        phpunit/phpunit:^11.3
        symfony/http-foundation:^7
        moneyphp/money:^4.6.0
